name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: sockets, json

      - name: "Validate composer.json and composer.lock"
        run: "composer validate --strict"

      - name: "Check code standard"
        run: "vendor/bin/phpcs"

      - name: "Run PHPStan"
        run: "vendor/bin/phpstan analyse"
